main: io.github.MGDCl.TheBridge.TheBridge
name: TheBridge
version: 2.5.0
authors: [Stefatorus, pintux98, Leonardo0013YT]
description: TheBridge edited by MGDCl
softdepend: [PlaceholderAPI, FastAsyncWorldEdit, WorldEdit]
commands:
  bridges:
    description: TheBridge minigame main command.
    aliases: [bridge, tb, thebridge]
permissions:
  bridges.join:
    default: true